name: kiggyshop
services:
  kiggyserve:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      - REMOTE_DATABASE_PATH=/var/lib/kiggyserve/data.sqlite
    volumes:
      - sqlite-data:/var/lib/kiggyshop
    ports:
      - 8080
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: ./fs-kiggyshop/Dockerfile
    volumes:
      - ./frontend/dist:/var/www/html/kiggyshop:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - kiggyserve
    networks:
      - webnet

volumes:
  sqlite-data:
  letsencrypt:

networks:
  webnet:
