[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
diesel = { version = "2.1.3", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
common = { version = "^0.1.0", path = "../common/", features = ["backend"]}
uuid = "1.5.0"
env_logger = "0.10.0"
actix-files = "0.6.2"
r2d2 = "0.8.10"
dotenv = "0.15.0"
async-stripe = {version = "0.25.2", features = ["runtime-tokio-hyper"]}
